### ISSUE TITLE
Openwrt自启动+进程守护

### ISSUE THREAD

**Issue by lovaladder** [naiba/nbdns#1]
dalao每次启动都要手动./nbdns 还有其他方法么

**Comment by naiba** [comment]
https://www.google.com/search?q=Openwrt%E8%87%AA%E5%90%AF%E5%8A%A8

**Comment by dysf888** [comment]
> dalao每次启动都要手动./nbdns 还有其他方法么

service

**Comment by naiba** [comment]
![image](https://user-images.githubusercontent.com/29243953/168213069-7e2723a8-729d-409d-99b7-550d6f02cd34.png)
